CREATE DATABASE MISSATGERIA;
USE MISSATGERIA;

CREATE TABLE USUARIS (
ID_USUARI INT(4) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NOM VARCHAR(25) NOT NULL,
PASSWORD VARCHAR(25) NOT NULL,
DARRER_MISSATGE TIMESTAMP NULL,
ONLINE TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MISSATGES (
ID_MISSATGE INT(9) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FK_ID_USUARI INT(4) UNSIGNED,
MISSATGE VARCHAR(100) NOT NULL,
DATA TIMESTAMP NOT NULL,
FOREIGN KEY (FK_ID_USUARI) REFERENCES USUARIS(ID_USUARI)
);


/*
INSERT INTO USUARIS (NOM, PASSWORD, DARRER_MISSATGE, ONLINE) VALUES ("TOMEU","TOMEU",NOW(),NOW());
INSERT INTO USUARIS (NOM, PASSWORD, DARRER_MISSATGE, ONLINE) VALUES ("RAMON","RAMON",NOW(),NOW());

*/